### ISSUE TITLE
made it easier to download the pure HTML file by adding download button on official website 

### ISSUE THREAD

**Issue by dinguschan-owo** [dinguschan-owo/dingusproxy#12]
go to the official website (https://dinguschan-owo.github.io/dingusproxy/) and click the download button in the top left corner, then open the file. you asked, I listened :333

**Comment by Project516** [comment]
I knew some idiots won’t extract the zip and the html file will be messed up. Thx

**Comment by dinguschan-owo** [comment]
> I knew some idiots won’t extract the zip and the html file will be messed up. Thx

anytime! I will add the alternate links section today, but please deploy from the main branch, not forks so I can add a verified symbol on the link

**Comment by Project516** [comment]
yo you added my deployment! thx! some other of my deployments are
-https://yee-eta.vercel.app
-https://yeedee.vercel.app
