### ISSUE TITLE
tools section

### ISSUE THREAD

**Issue by Project516** [dinguschan-owo/dingusproxy#27]
something like that with that encrypter u make and other stuff probably put in there too

**Comment by Project516** [comment]
i guess the terminal, githubsearch and image to css should go there (like the proxy is an all in one)

**Comment by dinguschan-owo** [comment]
nah, that's the plan for the terminal

**Comment by dinguschan-owo** [comment]
i was thinking about putting something like this, but its pretty cluttered to I think it'd be too much
