### ISSUE TITLE
UNBLOCKABLE dataurl link

### ISSUE THREAD

**Issue by dinguschan-owo** [dinguschan-owo/dingusproxy#29]
@Project516 this shouldn't be blockable, but please test it. its second from the bottom I nthe readme

https://github.com/dinguschan-owo/dingusproxy/blob/main/README.md

**Comment by Project516** [comment]
It doesn’t render the link (like if to put YouTube.com), and downloads don’t work cause no directory

**Comment by Project516** [comment]
But smart to use data:

**Comment by dinguschan-owo** [comment]
ok its fine ill use jsdeliver ill figure it out

**Comment by dinguschan-owo** [comment]
to be fixed
