### ISSUE TITLE
NEW VERSION OUT WITH CRAAAZY UPDATES

### ISSUE THREAD

**Issue by dinguschan-owo** [dinguschan-owo/dingusproxy#4]
### **USE THE NEW VERSION :D** 

@project516 I saw you starred this, so I figured I would push some new updates for u :D. Also, if you don't mind sharing this with some of your friends or associates it would be very much appreciated! Thanks for the star!

**Comment by Project516** [comment]
Your amazing

**Comment by dinguschan-owo** [comment]
Much appreciated! More updates on the way!
