### ISSUE TITLE
"blob:" cloaking got a little fucky wucky

### ISSUE THREAD

**Issue by dinguschan-owo** [dinguschan-owo/dingusproxy#8]

**Comment by Project516** [comment]
yep

**Comment by Project516** [comment]
but it works downloaded lol

**Comment by Project516** [comment]
oh because again no js or css only html

**Comment by dinguschan-owo** [comment]
yuppers

**Comment by Project516** [comment]
it could do a blob of the directory where the file is normally downloaded from

**Comment by dinguschan-owo** [comment]
good idea, I'll do that

**Comment by dinguschan-owo** [comment]
ok, itl first try and open a blob: url from the folder in the repo, then from the separate offline repo, then lastly of the old method if both others fail
